const WIDTH = 600
const HEIGHT = 300
const SCALE = 1
const DEVEICE_GAP_ICON_WIDTH = 4
const GAP_DEVICE_WIDTH = 10
const DEVEICEGAPICONHEIGHT = 3
const MODEL_GAP_BTN = 20
const CROSS_WALK_WIDTH = 3
const CROSS_SCALE_WALK_WIDTH = 15

export {
  WIDTH,
  HEIGHT,
  SCALE,
  DEVEICE_GAP_ICON_WIDTH,
  GAP_DEVICE_WIDTH,
  DEVEICEGAPICONHEIGHT,
  MODEL_GAP_BTN,
  CROSS_WALK_WIDTH,
  CROSS_SCALE_WALK_WIDTH
}
