const DIRECTION = {
  // NONE: 'NONE',
  STRAIGHT: 'STRAIGHT',
  STRAIGHT_LEFT: 'STRAIGHT_LEFT',
  STRAIGHT_RIGHT: 'STRAIGHT_RIGHT',
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  BACK: 'BACK',
  LEFT_BACK: 'LEFT_BACK',
  STRAIGHT_BACK: 'STRAIGHT_BACK',
  LEFT_RIGHT: 'LEFT_RIGHT'
}

export default DIRECTION
